ENH: Added exiting function for errors.
Added function to be used when there is an error detected.

Takes input for the message to be displayed when exiting. This is in
addition to the general message:

Call function:
__fault_detected_exit “Hawk of black are down.”

Output:
Critical error detected. Exiting for following reason:
Hawk of black are down.

diff --git a/sbin/chyves b/sbin/chyves
--- a/sbin/chyves
+++ b/sbin/chyves
@@ -9,6 +9,13 @@ _OFFLINE_POOLS_GREP_STRING=$(zfs get -H -o name,value -t filesystem -r chyves:da
 _TEMPLATE_GUESTS_GREP_STRING=$(zfs get -H -o name,value -t filesystem -r chyves:guest_role | grep "chyves/guests" | grep "template" | cut -d'/' -f1 | tr '\n' ' ' | sed -e 's/[[:space:]]*$//' | sed -e 's/ /\|/g')
 PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
 
+# Function used to exit with a message.
+__fault_detected_exit(){
+  local message="$1"
+  echo "Critical error detected. Exiting for following reason:"
+  echo "${message}"
+  exit 1
+}
 
 # See whether given command is readonly
 # and therefore doesn't need root credentials
